### ISSUE TITLE
is this line intentional? "nneofetch"

### ISSUE THREAD

**Issue by elvisisvan** [e811-py/MrZsh#1]
https://github.com/Mr3rf1/MrZsh/blob/b86b9a6ff2fb00df5d6d8a2a2623f91631ba5c99/MrZsh.sh#L95

line number 95 has the word "nneofetch" do you really mean it or is it actually "neofetch" (single "n")?

**Comment by Mr3rf1** [comment]
> https://github.com/Mr3rf1/MrZsh/blob/b86b9a6ff2fb00df5d6d8a2a2623f91631ba5c99/MrZsh.sh#L95
> 
> line number 95 has the word "nneofetch" do you really mean it or is it actually "neofetch" (single "n")?

it's "\n" to move cursor to next line and after that "neofetch" @elvisisvan
